<?php

/**
 * @file
 * gdpr_consent.module
 */

use Drupal\Component\Serialization\Json;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Link;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\gdpr_consent\Entity\DataPolicy;

/**
 * Implements hook_help().
 */
function gdpr_consent_help($route_name, RouteMatchInterface $route_match) {
  if ($route_name == 'entity.block.edit_form' && $route_match->getRawParameter('block') == 'gdpr_consent') {
    return '<p>' . t('Go to @url page for setting block title on specific pages.', [
      '@url' => Link::createFromRoute(t('Data usage explanation'), 'entity.informblock.collection')->toString(),
    ]) . '</p>';
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function gdpr_consent_form_user_register_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  $form['#attached']['library'][] = 'core/drupal.dialog.ajax';

  $link = Link::createFromRoute(t('data policy'), 'gdpr_consent.data_policy', [], [
    'attributes' => [
      'class' => ['use-ajax'],
      'data-dialog-type' => 'modal',
      'data-dialog-options' => Json::encode([
        'title' => t('Data policy'),
        'width' => 700,
        'height' => 700,
      ]),
    ],
  ]);

  $form['data_policy'] = [
    '#type' => 'checkbox',
    '#title' => t('I agree with the @url', [
      '@url' => $link->toString(),
    ]),
    '#required' => TRUE,
  ];
}

/**
 * Implements hook_ENTITY_TYPE_insert().
 */
function gdpr_consent_user_insert(EntityInterface $entity) {
  $data_policy = DataPolicy::create();

  /** @var \Drupal\user\UserInterface $entity */
  $data_policy->setOwner($entity);

  $data_policy->save();
}
