<?php

/**
 * @file
 * gdpr_consent.module
 */

use Drupal\Core\Link;
use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function gdpr_consent_help($route_name, RouteMatchInterface $route_match) {
  if ($route_name == 'entity.block.edit_form' && $route_match->getRawParameter('block') == 'gdpr_consent') {
    return '<p>' . t('Go to @url page for setting block title on specific pages.', [
      '@url' => Link::createFromRoute(t('Data usage explanation'), 'entity.informblock.collection')->toString(),
    ]) . '</p>';
  }
}
